apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres
  namespace: rails-k8s-app
spec:
  serviceName: "db"
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:15
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              value: myapp
            - name: POSTGRES_PASSWORD
              value: password
            - name: POSTGRES_DB
              value: myapp_development
