apiVersion: v1
kind: Service
metadata:
  name: rails-service
  namespace: rails-k8s-app
spec:
  selector:
    app: rails
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: NodePort  # Or ClusterIP if using port-forwarding
