apiVersion: apps/v1
kind: Deployment
metadata:
  name: rails-app
  namespace: rails-k8s-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rails-app
  template:
    metadata:
      labels:
        app: rails-app
    spec:
      containers:
      - name: rails-app
        image: your-dockerhub-username/rails-app:latest
        ports:
        - containerPort: 3000
        env:
        - name: DATABASE_HOST
          value: db
        - name: DATABASE_USER
          value: myuser
        - name: DATABASE_PASSWORD
          value: mypassword
        - name: DATABASE_NAME
          value: mydb

