apiVersion: apps/v1
kind: Deployment
metadata:
  name: rails-app
  namespace: rails-k8s-app  # ✅ Add this line
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rails
  template:
    metadata:
      labels:
        app: rails
    spec:
      containers:
      - name: rails
        image: rails-k8s-app:latest
        imagePullPolicy: IfNotPresent  # ✅ use local image built with Minikube
        ports:
        - containerPort: 3000
        env:
        - name: POSTGRES_USER
          value: "myapp"
        - name: POSTGRES_PASSWORD
          value: "password"
        - name: POSTGRES_DB
          value: "myapp_development"
        - name: POSTGRES_HOST
          value: "db"
