apiVersion: v1
kind: Service
metadata:
  name: rails-service
  namespace: rails-k8s-app
spec:
  selector:
    app: rails-app
  ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP
  type: NodePort
